language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "javierbrea"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

script:
  - npm run lint
  - npm run avoid-file-links
  - npm run test
  - npm run coveralls
  - sonar-scanner -Dsonar.login=${SONAR_TOKEN}

deploy:
  provider: npm
  email: "javier.brea@gmail.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  skip_cleanup: true
